### ISSUE TITLE
[FR] Allow to change the clock position to the center of the status bar when Network traffic monitor is enabled 

### ISSUE THREAD

**Issue by Charlie-117** [ProjectSakura/Bug_Tracker#1]
**Describe the feature:**
When the Status bar Clock position is set to centre , the option to enable Network traffic monitor disappears.
Please add this feature because the traffic monitor at the centre looks weird and should instead be placed on left or right side.(at least in my opinion)

**Links to commits (if applicable):**
https://github.com/crdroidandroid/android_frameworks_base/commit/10ee0c00bc92cf471b409a73b0cfde133a3a2b04
https://github.com/crdroidandroid/android_frameworks_base/commit/5e0404f6f4ad2377f67da5e5211691c853eee863 (is this the one ??)
 ( *Apologies if this is not the required commit* )

**Additional information**
I have attached a screenshot of this feature.

![photo_2020-07-17_12-36-11](https://user-images.githubusercontent.com/66198164/87758324-dde1d280-c829-11ea-8863-ea20588d619a.jpg)

**Comment by LordShenron** [comment]
This is completed in the new Android 11 release.
