### ISSUE TITLE
[FR] Hide notch option

### ISSUE THREAD

**Issue by ket0x4** [ProjectSakura/Bug_Tracker#10]
**Describe the feature:**
Some Roms have option called "Hide notch" we can hide completely or switch between immersive, hide, normal modes.

**Links to commits (if applicable):**
POSP have this feature: https://github.com/PotatoProject

**Additional information**
https://www.youtube.com/watch?v=PUiGWtKZ6Hw (not my video)

**Comment by LordShenron** [comment]
We had this feature in A10 based builds and this will be ported to A11 in future builds too.
