### ISSUE TITLE
[BUG] BT does not work on whyred A11 

### ISSUE THREAD

**Issue by pippo73** [ProjectSakura/Bug_Tracker#12]
**About the Bug.**
Cannot turn on the Bluetooth 

**How to reproduce it.**

1. Turn on BT in settings menu or with the button in the top of the screen 

**Expected behaviour of the feature without bug.**

Bluetooth should work 

**Logs while recreating the bug.**

**Screenshots if applicable**

**What Device are you using?**

 - Codename (ex. X00T):  whyred 
 - Build date and ID :  09/ Jan /2021

**Additional information**

**Comment by LordShenron** [comment]
If it's a device specific bug then contact your maintainer, in you case it's @Sweeto143

**Comment by Darkstar085** [comment]
Demn.. Will check..

**Comment by pippo73** [comment]
Thank you
