### ISSUE TITLE
Recent / Multitask drawer overshoots bug

### ISSUE THREAD

**Issue by tarsonis123** [ProjectSakura/Bug_Tracker#13]
The bug happens randomly. Every 7-10 times. I use the 2 button navigation with navbar. Would like to add some log but dunno where those are. 
Latest build with a Meizu 16th. The ROM is installed today so no customized 3rd party tweaks.
![Screenshot_20210120-021239_OnePlus_Launcher](https://user-images.githubusercontent.com/13262445/105113555-743acd80-5ac5-11eb-8b76-652f45873efd.png)

**Comment by LordShenron** [comment]
Android 10 is already discontinued. The sources are not updated anymore.

**Comment by tarsonis123** [comment]
Well that doesn't disqualify that behavior as a bug. Didn't have this issue with Mokee for instance which seem to use the same recent window drawing. Unfortunately there is no Android 11 rom for the Meiz so I use what I get.

**Comment by LordShenron** [comment]
> Well that doesn't disqualify that behavior as a bug. Didn't have this issue with Mokee for instance which seem to use the same recent window drawing. Unfortunately there is no Android 11 rom for the Meiz so I use what I get.

We don't update A10 anymore so this don't qualify as a bug for us anymore unfortunately and I can't/won't fix it. All i can recommend is moving to A11 builds that don't have this issue reported so far.

**Comment by tarsonis123** [comment]
OK any plan to offer ProjectSakura A11 for the m1182 / Meizu 16th?
