### ISSUE TITLE
[BUG] wrong toggling of traffic indicator arrows

### ISSUE THREAD

**Issue by m-rey** [ProjectSakura/Bug_Tracker#14]
**About the Bug.**
When using the "Hide Arrows" toggle in `Settings -> Sakura Configs -> Interface -> traffic indicators`, the option does the opposite of what its description says: When the "hide arrows" option is activated, the arrows are _shown_. When it's deactivated, they are _hidden_. 

**How to reproduce it.**

1. Go to `Settings -> Sakura Configs -> Interface -> traffic indicators`
2. Set the "net activity aurohide threshold to 0 to always see the traffic indicator (for better debugging) 
3. Toggle the "hide arrows" option a few times and notice how and when it hides and shows the arrows.

**Expected behaviour of the feature without bug.**
Two ways of fixing the bug. Choose one of them:

* Arrows should be hidden when the "hide arrows" option is on, and shown when the option is off.

* Change the label text of the option to "show arrows". 

**Screenshots if applicable**
![Hide arrows option is off, but arrows are hidden](https://user-images.githubusercontent.com/42996147/105758171-3c150e00-5f4f-11eb-8c42-8787ddf45168.png)
![Hide arrows option is on, but arrows are shown](https://user-images.githubusercontent.com/42996147/105758322-68c92580-5f4f-11eb-918b-2cb9ce65dcb2.png)

**What Device are you using?**

 - Codename (ex. X00T):  tucana
 - Build date and ID :  2021-01-18, RQ1A.210105.003 (bug was also in the previous release)
 
My educated guess is that this bug concerns all devices, but I only have a tucana available and thus was only able to confirm the bug for the tucana release.

**Comment by LordShenron** [comment]
Thanks for the tip.. It will be properly named in next release.

**Comment by LordShenron** [comment]
This issue is now fixed, So closing this now.
