### ISSUE TITLE
[BUG] Some setting changes aren't persistent (e.g. Wi-Fi network autoconnect)

### ISSUE THREAD

**Issue by m-rey** [ProjectSakura/Bug_Tracker#16]
**About the Bug.**
With some settings, when you modify them and then close and reopen settings, the previously modified options are back to the value they were before you modified them. It thus looks like the changes simply aren't saved. This bug does only apply to some options, but on the settings where it does, it does consistently.

For example, some Wi-Fi network configuration options like autoconnect aren't saved/persistent.

**How to reproduce it.**

For the autoconnect issue:
1. Connect to a Wi-Fi network
2. Open the network details of the connected WiFi hotspot
3. Enable the autoconnect option
4. Leave settings
5. Disable Wi-Fi in quick settings
6. Enable Wi-Fi in quick settings
7. The phone doesn't autoconnect to the saved network.
8. Navigate to the Wi-Fi network details
9. The previously enabled autoconnect setting is disabled.

**Expected behaviour of the feature without bug.**

Changes in settings should be kept. 

**Screenshots if applicable**

The following screenshots show how to reproduce the issue for Wi-Fi network autoconnect:
1. go to Wi-Fi settings ![Screenshot_20210125-212440_Settings](https://user-images.githubusercontent.com/42996147/105766498-1f320800-5f5a-11eb-813e-9bb45bed7516.png)
2. connect to network ![Screenshot_20210125-212756_Settings](https://user-images.githubusercontent.com/42996147/105766778-71732900-5f5a-11eb-9981-491f1be77a04.png)
3. open network settings ![Screenshot_20210125-212824_Settings](https://user-images.githubusercontent.com/42996147/105766566-3670f580-5f5a-11eb-9c79-46d4e0f25221.png)
4. activate "autoconnect" 
![Screenshot_20210125-212846_Settings](https://user-images.githubusercontent.com/42996147/105766971-b5fec480-5f5a-11eb-94d6-852daba618a2.png)
5. go out of network details 
![Screenshot_20210125-212756_Settings](https://user-images.githubusercontent.com/42996147/105767082-e9415380-5f5a-11eb-9875-4105679e4ca2.png)
6. go back to network details. Autoconnect is disabled 
![Screenshot_20210125-212824_Settings](https://user-images.githubusercontent.com/42996147/105767183-09711280-5f5b-11eb-9ee1-fbfe007746ea.png)

**What Device are you using?**

 - Codename (ex. X00T):  tucana
 - Build date and ID :  2021-01-18, RQ1A.210105.003 (bug was also in the previous release)
 

**Additional information**

I'm unsure if this only happens on tucana or also on other devices.

I've mentioned that the issue also happens with other settings. If you need more examples, just say so. I'll try  to find and document further situations where this happens.

**Comment by LordShenron** [comment]
This seems to be a device specific issue.
