### ISSUE TITLE
[BUG] quick settings bug

### ISSUE THREAD

**Issue by Sleppyiecat** [ProjectSakura/Bug_Tracker#18]
**About the Bug.**
Once you will use quick settings banner, then all expanded menus like wifi or bluetooth things are kinda weird, you can just test yourself

**How to reproduce it.**

1. enable quick settings banner
2. click arrow next to icons, this text should be hidden

**Expected behaviour of the feature without bug.**
the text above menu should be hidden, bar is too small i guess.

**Screenshots if applicable**
here -> https://prnt.sc/zypm75

**Comment by LordShenron** [comment]
Patched for now.. not with a very good method but it's fixed for now.
[image](https://i.imgur.com/XtJIAK7.jpg)
