### ISSUE TITLE
[BUG] bubles crashing

### ISSUE THREAD

**Issue by Sleppyiecat** [ProjectSakura/Bug_Tracker#19]
**About the Bug.**

**How to reproduce it.**

1. Open messenger app
2. start chat in bubles, sometimes it crash straight up, sometimes you need to click for some time

**Expected behaviour of the feature without bug.**

dont crash ui?

**Logs while recreating the bug.**

http://www.mediafire.com/file/0oz8q7rgx6mdfia/logcat.txt/file

**What Device are you using?**

 - Codename (ex. X00T):  davinci 
 - Build date and ID :  18/0/2021

**Additional information**

its not device issue i guess, as issue is related to inputDispatcher in frameworks/natives

**Comment by LordShenron** [comment]
Well the culprit was AOKP system animations all this time. 
This issue is fixed so closing it now.
