### ISSUE TITLE
[Face unlock] pls add swipe to face unlock at lock screen

### ISSUE THREAD

**Issue by 1Rajat1** [ProjectSakura/Bug_Tracker#20]
**Describe the feature:**

**Links to commits (if applicable):**

**Additional information**

NOTE: WE DON'T PROVIDE ANY ETA ON WHEN THIS WILL BE ADDED.

**Comment by LordShenron** [comment]
This is added with the recent faceunlock changes.

**Comment by 1Rajat1** [comment]
OK. Thank you
