### ISSUE TITLE
[BUG]Trebuchet force stopping after clicking 'App info' from recent screen in any launcher other than Trebuchet

### ISSUE THREAD

**Issue by PROxZIMA** [ProjectSakura/Bug_Tracker#21]
**About the Bug.**
Trebuchet launcher (default launcher) force stopping after clicking `App info` from recent screen in any launcher other than Trebuchet launcher itself

**How to reproduce it.**

1. Switch to any launcher other than Trebuchet and make it default.
2. Go to recent screen and click `App icon`
3. Select `App info` from the drop down (nothing happens and home screen appears)
4. Repeat step 2 and 3 again. A dialogue box pops up saying `Trebuchet keeps stopping`

**Expected behaviour of the feature without bug.**

Selecting `App info` in Trebuchet shows a small popup related to app having last option as app info from settings.
Selecting `App info` from other launcher should either return a popup as in Trebuchet or open the app's info in settings.

**Logs while recreating the bug.**

https://del.dog/raydogrolo.txt

**Screenshots if applicable**

<img src="https://user-images.githubusercontent.com/43103163/110980055-6c8ffa80-838b-11eb-92c9-28dc7b0d164c.png" width="300px">

**What Device are you using?**

 - Codename (ex. X00T) :  X00TD
 - Build date :  08/03/2021
 - Build ID :  RQ2A.210305.006

**Additional information**

NONE

**Comment by LordShenron** [comment]
This issue is fixed with this commit ->
https://github.com/ProjectSakura/packages_apps_Trebuchet/commit/3a98f82037440cfe6611d04c87e9552ceec6f4f7
