### ISSUE TITLE
[BUG] Sensitivity options of navigation gestures

### ISSUE THREAD

**Issue by Sleppyiecat** [ProjectSakura/Bug_Tracker#22]
**About the Bug.**
lowest sensitivity disable back gestures completly

**How to reproduce it.**

1. go to gesture navigation and to settings of gestures
2. set sensitivity of back gestures to low

**Expected behaviour of the feature without bug.**

well is should work, not disable back gestures completly

**Comment by LordShenron** [comment]
Hmm hmm, I will look into this one first
