### ISSUE TITLE
[BUG] Mizu theme not working properly

### ISSUE THREAD

**Issue by IAGM12** [ProjectSakura/Bug_Tracker#24]
**Mizu theme in Dark mode, force close the Settings app**

****

1. Apply Mizu on Interface within Sakura Settings
2. Trying to change the font size or DPI size, close and reopens Settings

**What Device are you using?**

 - Codename (ex. X00T):  Ginkgo
 - Build date and ID : 20200321

**Comment by LordShenron** [comment]
A logcat will be more helpful

**Comment by LordShenron** [comment]
https://github.com/ProjectSakura/vendor_sakura/commit/b88b6d5f9a0e6ebdb86d38664ba329c2af88cd43
Fixes this issue.
