### ISSUE TITLE
[BUG] back gesture sensitivity

### ISSUE THREAD

**Issue by abadi718** [ProjectSakura/Bug_Tracker#25]
**About the Bug.**
Left edge and right edge can't be at third level it always goes to high as shown in the video below
 

**Expected behaviour of the feature without bug.**

It should remain at third level not forth(high)

**Screenshots if applicable**

**What Device are you using?**

https://user-images.githubusercontent.com/60826707/119725379-887a4700-be78-11eb-9391-37f8269390b2.mp4

 - Galaxy note 8 n950f

**Comment by LordShenron** [comment]
I see.. I will check what can be done here
