### ISSUE TITLE
[BUG] Device inspect not working with Chrome

### ISSUE THREAD

**Issue by Albvadi** [ProjectSakura/Bug_Tracker#26]
**About the Bug.**
The device isn´t appearing in the devices inspection in Google Chrome (PC)

**How to reproduce it.**
1. (Smartphone) Enable developer options menu
2. (Smartphone) Enable USB debugging
2. (Smartphone) Install Google Chrome web browser
3. (Smartphone) Open any web in Google Chrome
3. (PC) Autorize adb with `adb devices` and accepting the connection
4. (PC) In Chrome, go to `chrome://inspect`

**Expected behaviour of the feature without bug.**
The device it's recognized but not detect the open of Google Chrome

**Expected behaviour**
![2021-05-27_10_58_06](https://user-images.githubusercontent.com/6285255/119804798-f8241c80-bee0-11eb-8251-34876cba474a.png)

**Actual behaviour**
![2021-05-27_11_57_21](https://user-images.githubusercontent.com/6285255/119806693-ba27f800-bee2-11eb-85d0-e3159cd2784f.png)

**What Device are you using?**
 - Codename (ex. X00T):  SM-G950F (Samsung Galaxy S8)
 - Build date and ID :  Latest 5.R | Android 11 - Updated 25/May/2021

**Additional information**
I tested with many others roms and the results differs:

- Havoc 4.2 and 4.3: not working
- HadesRom Q 1.0: working
- LineageOs 17.1 and 18.1: working

I know this is a niche feature, but it´s very useful when you develop hibryd apps...

Thank you!

**Comment by LordShenron** [comment]
@haridhayal11 can you confirm this issue?

**Comment by LordShenron** [comment]
Okay I tried replicating the issue today and I can acknowledge it, luckily I also had a device running havoc OS with Android 10 and it wasn't work there too. I will investigate more into it.
