### ISSUE TITLE
[FR] please add IME cursor support to the Google keyboard  (Gboard). Meant are two buttons (left and right arrow) at the bottom like Havoc ROM does it. 

### ISSUE THREAD

**Issue by VoRo1** [ProjectSakura/Bug_Tracker#27]
**Describe the feature:**

**Links to commits (if applicable):**

**Additional information**

NOTE: WE DON'T PROVIDE ANY ETA ON WHEN THIS WILL BE ADDED.

**Comment by LordShenron** [comment]
We don't plan to have this.
