### ISSUE TITLE
[FR] Ability to switch off a sim card in network settings

### ISSUE THREAD

**Issue by alexphilip0019** [ProjectSakura/Bug_Tracker#29]
**Describe the feature:**
Feature was available in A10. In network settings under each sim there was a toggle to switch off sim.

**Additional information**
 
![Screenshot_20210630-215037_Settings](https://user-images.githubusercontent.com/25505145/123996974-85c9bf00-d9ed-11eb-9296-caac2c2ed6b7.png)

Need a toggle somewhere like in area marked in screenshot

**Comment by LordShenron** [comment]
This feature won't be added.
