### ISSUE TITLE
[FR] Please consider these 10 requests. 

### ISSUE THREAD

**Issue by AkashXceptional** [ProjectSakura/Bug_Tracker#3]
01. Add option to hide vpn symbol from status bar.
02. Add option for getting old style network indicator.
03. Add a NFC indicator
04. Add an option to reset battery stats
05. Add date option for status bar clock
06. Remove HD capable notification
07. Add Trebuchet launcher eitheras primary or as a choice
08. Add a logo option
09. Add an option to change accent colour
10. Add tiled type of volume panel

Thank you!

**Comment by LordShenron** [comment]
There will be no trebuchet. You can change accent color in Styles in wallpaper app. Rest we can consider with time.
