### ISSUE TITLE
[FR] Option to change brightness slider's position

### ISSUE THREAD

**Issue by sattanica** [ProjectSakura/Bug_Tracker#30]
**Describe the feature:**
An option to switch the brightness  slider's position to bottom. It’s  a very useful feature for one handed use. Many other roms like aex, ancient os, havoc os, nusantara, corvus has this feature. Hope to see this in Project Sakura also.

**Links to commits (if applicable):**

**Additional information**
![Screenshot_20210701-020311_Chrome.png](https://user-images.githubusercontent.com/86735881/124024582-36958580-da11-11eb-93ad-7c7a2b64aac5.png)

NOTE: WE DON'T PROVIDE ANY ETA ON WHEN THIS WILL BE ADDED.

**Comment by LordShenron** [comment]
We have decided not to do this.
