### ISSUE TITLE
Request to add back the option of "do not validate" under CA certificate in wifi

### ISSUE THREAD

**Issue by Mayank-Chhaperwal** [ProjectSakura/Bug_Tracker#32]
**Describe the feature:**
In android 11, google removed the option to select "do not validate" when connecting to wifi. Refer: https://www.xda-developers.com/android-11-break-enterprise-wifi-connection/
This option has been added back in some of the custom roms such as ColtOS. Kindly add in Sakura too.

**Additional information**
Screenshots in the xda article.

NOTE: WE DON'T PROVIDE ANY ETA ON WHEN THIS WILL BE ADDED.

**Comment by LordShenron** [comment]
The change https://github.com/ProjectSakura/packages_apps_Settings/commit/15255cf75cd22389bd0a7cdcb1c59fd2744c314d
should bring back the needed settings.
