### ISSUE TITLE
[BUG] loud speaker volume always 100% The slider can change but do nothing 

### ISSUE THREAD

**Issue by HTCME** [ProjectSakura/Bug_Tracker#35]
**Can't change loud speaker volume always 100%
The slider can change but do nothing 

**Expected behaviour of the feature without bug.**

Fix the volume of phone loud speaker slider

**Logs while recreating the bug.**

**Screenshots if applicable**

**What Device are you using?**
Device leeco x520 s2
Project Sakura 5.1 vanila

**Additional information**

**Comment by anoosragh69** [comment]
Seems like a device specific issue, this is for source related bug tracking
