### ISSUE TITLE
Adding a volume stepper or configuration[FR]

### ISSUE THREAD

**Issue by damocamo** [ProjectSakura/Bug_Tracker#4]
**Describe the feature:**
The ability to change the volume steps in a configuration. At the moment pressing vol up or down goes by ~7 increments.

**Comment by LordShenron** [comment]
I will look into this during Android 11 now, For Android 10 I will not be making any new changes anymore.

**Comment by LordShenron** [comment]
This feature is added in Latest 4.R builds of Project Sakura.
