### ISSUE TITLE
[BUG] Android Auto couldn't connect to car

### ISSUE THREAD

**Issue by hkalman** [ProjectSakura/Bug_Tracker#5]
**About the Bug.**

Android Auto starts on my phone automatically when I connect it to the car. The car detects the Android Auto app and then tries to connect but the operation fails. There is no error message on the phone.

**How to reproduce it.**

1. Install this rom on Samsung Note 8 SM-N950F
2. Install the Android Auto
3. Try to connect to a car :) 

**Expected behaviour of the feature without bug.**

**Logs while recreating the bug.**

**Screenshots if applicable**

**What Device are you using?**

 - Codename (ex. X00T):  greatle
 - Build date and ID :  QQ3A.200805.001

**Additional information**

**Comment by LordShenron** [comment]
Thanks for reporting, It would be helpful if you could add a logcat for this. 
You can use adb or catlog for taking logs

**Comment by Davidprou** [comment]
I am having the exact same problem , tried different head units but all do the same.  

````csharp
09-06 19:01:11.502 27202 27202 E AndroidRuntime: FATAL EXCEPTION: main
09-06 19:01:11.502 27202 27202 E AndroidRuntime: Process: com.google.android.gms:car, PID: 27202
09-06 19:01:11.502 27202 27202 E AndroidRuntime: java.lang.RuntimeException: registerAudioPolicy failed -1
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nzp.<init>(:com.google.android.gms@203019037@20.30.19 (120400-326531024):10)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nll.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):75)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at omh.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):13)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nqt.ad(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nsk.ad(:com.google.android.gms@203019037@20.30.19 (120400-326531024):0)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nrj.j(:com.google.android.gms@203019037@20.30.19 (120400-326531024):10)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nra.run(Unknown Source:0)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at aesi.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):2)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at aesi.dispatchMessage(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7355 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940 undefined)
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	Suppressed: bocn:
09-06 19:01:11.502 27202 27202 E AndroidRuntime: 		at tk_trace.car-IStartupServiceCallback_5(Unknown Source:0)

`

**Comment by LordShenron** [comment]
> I am having the exact same problem , tried different head units but all do the same.
> 
> ```cs
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: FATAL EXCEPTION: main
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: Process: com.google.android.gms:car, PID: 27202
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: java.lang.RuntimeException: registerAudioPolicy failed -1
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nzp.<init>(:com.google.android.gms@203019037@20.30.19 (120400-326531024):10)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nll.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):75)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at omh.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):13)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nqt.ad(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nsk.ad(:com.google.android.gms@203019037@20.30.19 (120400-326531024):0)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nrj.j(:com.google.android.gms@203019037@20.30.19 (120400-326531024):10)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at nra.run(Unknown Source:0)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at aesi.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):2)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at aesi.dispatchMessage(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7355 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940 undefined)
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 	Suppressed: bocn:
> 09-06 19:01:11.502 27202 27202 E AndroidRuntime: 		at tk_trace.car-IStartupServiceCallback_5(Unknown Source:0)
> 
> `
> ```

It will be useful if you could attach a full log instead of a scraped one. Just try to connect using Android Auto while taking a log and attach that log file here.

**Comment by haridhayal11** [comment]
> **About the Bug.**
> 
> Android Auto starts on my phone automatically when I connect it to the car. The car detects the Android Auto app and then tries to connect but the operation fails. There is no error message on the phone.
> 
> **How to reproduce it.**
> 
> 1. Install this rom on Samsung Note 8 SM-N950F
> 2. Install the Android Auto
> 3. Try to connect to a car :)
> 
> **Expected behaviour of the feature without bug.**
> 
> **Logs while recreating the bug.**
> 
> **Screenshots if applicable**
> 
> **What Device are you using?**
> 
> * Codename (ex. X00T):  greatle
> * Build date and ID :  QQ3A.200805.001
> 
> **Additional information**




This is a device specific issue. Exynos 8895 device trees have this issue. All aosp roms for exynos 8895 devices have this problem. It is not fixable at least for me. If you want android auto, you better stick to stock (One-UI) based ROMs.

**Comment by hkalman** [comment]
Thanks a lot for this very important info :)
