### ISSUE TITLE
Volume buttons not working if display is off. Device [X00T]

### ISSUE THREAD

**Issue by sapnokior** [ProjectSakura/Bug_Tracker#9]
Sometimes when I press volume button and if screen is lock then its not working. Also sometimes display is on and when I long press volume key to increase volume continuously that also not work. I always use YouTube Music but I don't think these all bugs are happening with it.

**Comment by LordShenron** [comment]
So, you are saying it's happening in all apps except for youtube music? And where is the logcat.

**Comment by sapnokior** [comment]
No, this happening all time.. scree on bug = if volume button is long pressed then it's not raising volume whereas it's just raising only one step.

Screen off bug = no effect of volume button (single press or long press)

Sorry I can't provide logcat at this time but I will soon thanks.

**Comment by LordShenron** [comment]
As per my testing of the latest build checked with spotify, buttons now work with screen off too.
